version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    ports:
      - "5173:4173"
